name: Tag on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
          echo "LAST_TAG=$TAG" >> $GITHUB_ENV

      - name: Determine next version
        id: versioning
        run: |
          IFS='.' read -r -a parts <<< "${LAST_TAG//v/}"
          PATCH=$((parts[2] + 1))
          NEW_TAG="v${parts[0]}.${parts[1]}.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
