name: Continous Integration

on: 
  pull_request:
    branches:
      - ['main']
  
  push:
    branches:
      - ['main']

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2